### ISSUE TITLE
Caught objects don't stop 2.0

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/balancing-act#113] opened 2020-02-03 23:15 UTC
For https://github.com/phetsims/QA/issues/473. Can't determine if it applies to https://github.com/phetsims/QA/issues/462 since speed query parameter doesn't seem to work there. Similar to https://github.com/phetsims/balancing-act/issues/43 but with a few extra steps.

In order to reproduce this in https://github.com/phetsims/QA/issues/473:
1. set speed slow with querry parameter
2. Drag an object to far left of screen and let go
3. (Important) Turn the supports on the balance off and then on again before object makes it back to the box
4. Drag the object around as in the original issue.

![canstilldothisabit](https://user-images.githubusercontent.com/41024075/73699167-5bf95500-46a0-11ea-8779-82058c31082b.gif)

**Comment by jbphet** [comment] 2020-02-28 22:23
I'm not sure why this is a valid test.  Is slow speed as a query parameter supposed to be supported by this sim?  Is this something new?  Is it specific to the 1.2 "special" version that was requested?  Does the problem exist on master?

@KatieWoe - please help me to understand why this was created and assigned to me.

**Comment by KatieWoe** [comment] 2020-02-28 22:26
I've gotten it to happen at normal speed, but it is much, much easier to reproduce with the query parameter. The slow speed query parameter gives you more time to do all the steps. It isn't new exactly. I noted that it was similar to https://github.com/phetsims/balancing-act/issues/43. I think this method is limited to the special version as it relies on the behavior when you take the supports out, which is unique to this version.

**Comment by KatieWoe** [comment] 2020-02-28 22:27
I assigned you @jbphet since it was so similar to #43.

**Comment by jbphet** [comment] 2021-02-18 19:56
I think some of the work done for #126 and #43 may have fixed this issue due to the modifications made to drag handling.  @KatieWoe - please check and see whether this appears to be fixed on master.

**Comment by KatieWoe** [comment] 2021-02-18 21:37
I wasn't able to reproduce in master, but as mentioned in https://github.com/phetsims/balancing-act/issues/113#issuecomment-592757786, this may be related to behavior that was specific to the version being tested at the time.

**Comment by marlitas** [comment] 2023-11-30 22:48
It looks like this is ready to go for the upcoming publication. I will double check that I can't reproduce on main, and then close.

**Comment by AgustinVallejo** [comment] 2024-01-02 20:53
Wasn't able to reproduce either. Closing.

**Closed by AgustinVallejo** 2024-01-02 20:53 UTC
Labels: type:bug, status:fixed-awaiting-deploy
