### ISSUE TITLE
Playback fails

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/balancing-act#111] opened 2020-01-31 23:23 UTC
For https://github.com/phetsims/QA/issues/473. On Win 10 Chrome. 
I made a recording of the sim and when it was put in the playback wrapper it did not load past the loading bar. Here is the console:
![playbackfail](https://user-images.githubusercontent.com/41024075/73581295-ebef9280-4445-11ea-83a6-400a93df8ec4.png)

**Comment by KatieWoe** [comment] 2020-02-03 21:16
https://phet-dev.colorado.edu/html/balancing-act/1.2.0-rc.1/phet-io/wrappers/record/?console&stanford&screens=2

**Comment by KatieWoe** [comment] 2020-02-03 21:16
https://phet-dev.colorado.edu/html/balancing-act/1.2.0-rc.1/phet-io/wrappers/playback/?stanford&screens=2

**Comment by zepumph** [comment] 2020-02-03 21:28
This error is because of the query parameters for the playback wrapper are getting passed through to the recorded sim link, thus duplicating them. 

The playback wrapper shouldn't be doing this. I'll see what the trouble is.

**Comment by zepumph** [comment] 2020-02-03 21:37
@chrisklus can you please review this patch. The playback wrapper is old code, and this is untested, but it looks like it was manually tacking on top level search and passing it to the sim. We have never had a use case for that in the playback wrapper as far as I remember, and it would be nice to fix it. Can you review my patch (which isn't passing lint right now), and let me know what you think?

Let me know if you want a bit of a tour of the wrapper, as this may be your first time in there.

<details>

```diff
Index: playback/js/playSession.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- playback/js/playSession.js	(revision 71c7d09051aea38724df4c77cf2ce4b690669be0)
+++ playback/js/playSession.js	(date 1580765767993)
@@ -231,18 +231,6 @@
       }
     } );
 
-    // If there are new parameters
-    newSearch = ( window.location.search.substring( 1 ) ) ?
-                newSearch + '&' + window.location.search.substring( 1 ) :
-                newSearch;
-
-    // substring 1 to get past the '?'
-    if ( window.location.search.substring( 1 ) ) {
-
-      // Make sure that no query parameters are repeated, like ea in the top search and in the recorded sim url.
-      newSearch = combineNoDuplicates( window.location.search.substring( 1 ), newSearch );
-    }
-
     // Or specify a downloaded version here with ?production
     destinationFrame.src = `${urlNoSearch}?showPointers${newSearch}`;
   };

```
</details>

**Comment by chrisklus** [comment] 2020-02-04 04:24
I was able to reproduce the problem on my end before applying the patch (with a built version), and can confirm that the error is gone after applying the patch. I updated the patch to remove the lint error.

Do we need to discuss why query parameters may or may not need to be passed through before proceeding?

<details>

```diff
Index: playback/js/playSession.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- playback/js/playSession.js	(revision 7bf9778a20365b51a6ec60da04b6ed716d9abf93)
+++ playback/js/playSession.js	(date 1580788109000)
@@ -164,31 +164,6 @@
     session.queueEventObjects( forPlayback );
   };
 
-  /**
-   *
-   * Combine two lists into one and return the list. There should be no duplicates.
-   * @param {Array} list1
-   * @param {Array} list2
-   * @returns {Array} - list2 with non-duplicated members of list1
-   */
-  const combineNoDuplicates = ( list1, list2 ) => {
-    for ( let i = 0; i < list1.length; i++ ) {
-      const parameter = list1[ i ];
-      let isDuplicate = false;
-
-      for ( let j = 0; j < list2.length; j++ ) {
-        const newParameter = list2[ j ];
-        if ( parameter === newParameter ) {
-          isDuplicate = true;
-        }
-      }
-
-      // It wasn't in any of list2
-      !isDuplicate && list2.push( parameter );
-    }
-    return list2;
-  };
-
   /**
    * Set the url of the sim used in the log file to the iframe src. Most of the logic here revolves around filtering
    * query parameters to be passed from the parent page into the sim url.
@@ -231,18 +206,6 @@
       }
     } );
 
-    // If there are new parameters
-    newSearch = ( window.location.search.substring( 1 ) ) ?
-                newSearch + '&' + window.location.search.substring( 1 ) :
-                newSearch;
-
-    // substring 1 to get past the '?'
-    if ( window.location.search.substring( 1 ) ) {
-
-      // Make sure that no query parameters are repeated, like ea in the top search and in the recorded sim url.
-      newSearch = combineNoDuplicates( window.location.search.substring( 1 ), newSearch );
-    }
-
     // Or specify a downloaded version here with ?production
     destinationFrame.src = `${urlNoSearch}?showPointers${newSearch}`;
   };

```

</details>

**Comment by chrisklus** [comment] 2020-02-04 04:25
Related to https://github.com/phetsims/phet-io-wrappers/issues/305

**Comment by zepumph** [comment] 2020-02-04 23:42
>https://github.com/phetsims/phet-io-wrappers/issues/305

Nice find thank you!


>Do we need to discuss why query parameters may or may not need to be passed through before proceeding?

I can't think of a good reason to pass through query parameters from the playback wrapper into the sim being played back. In fact, I know that in general we rely heavily and using the exact URL that was used when recording (which is saved in the data log's `simStarted` event. This is vital for obvious reasons (i.e. like making sure that the `?standford` QP is there when needed. This could drastically break playback. 

From this is seems strange that there would be support for adjusting the playback URL to be different from that which was used to record. Perhaps when we (naive little Michael) were developing it, we thought that it could be a nice feature. Even so, I can't recall ever actually purposefully passing through a parameter in the last three years, and thus I feel very good about removing this now.

I committed above, let me know what you think? If we go ahead with the commit, then we should likely add this to gravity-force-lab too.

**Comment by chrisklus** [comment] 2020-02-05 00:17
Nice, that reasoning sounds great to me. I too was thinking that the query strings should match exactly like you said (and can't think of a reason why any would need to be added), so it's good to hear that this feature may have not been done for a specific reason and that you don't remember ever intentionally passing through additional sim QPs. Ready to close once that sha is added to GFL?

**Comment by zepumph** [comment] 2020-02-19 20:43
To test this on GFL, you can add a the queryParameter `?phetioDebug` when recording to a local file. (this will add the `?ea` query parameter to the sim`, then during playback (in the playback wrapper) add the `?ea` query parameter to the playback wrapper. In rc.1 this should fail, but it should be fixed in rc.2 and on master.

Thanks!

**Comment by KatieWoe** [comment] 2020-02-24 16:22
Looks good. Tested Win 10 chrome rc.2

**Closed** 2020-02-24 19:11 UTC
Labels: status:ready-for-qa, type:bug
