### ISSUE TITLE
Problem with not being able to drag objects or click buttons after incorrect answer

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/balancing-act#62] opened 2016-01-22 19:24 UTC
Test device: Dirac

Operating System: OS X 10.11.2

Browser: Safari, Chrome

Problem description: When in the game section, if you guess the wrong answer on one of the "What is the mass?" games, sometimes (not always) after you click try again, you will not be able to drag the weight, drag the slider, or click the arrow buttons, so you just have to start over or check the same wrong answer to move on. This happens more often when the weight you drag is not the red blocks, but something like a rock, but it can still happen with the red blocks. 

Steps to reproduce: Go into games, any level and play through until you find one that is "What is the mass?" On that one, guess the wrong answer, and check it. After you click try again, it is likely that you will not be able to drag the mass or slider, or click the arrow buttons. This may not happen every time though.

Screenshots:
![balancingact](https://cloud.githubusercontent.com/assets/11947677/12520616/cd688ce2-c102-11e5-91a9-bc9008a2162d.gif)

Troubleshooting information (do not edit):
Name: ‪Balancing Act‬
URL: http://phettest.colorado.edu/balancing-act/balancing-act_en.html?ea&brand=phet
Version: 1.1.0-dev.1 (require.js)
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36
Language: en-US
Window: 1058x582
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

Related to phetsims/tasks#479

**Comment by jbphet** [comment] 2016-03-07 20:21
This is a duplicate of #55 - closing.

**Closed by jbphet** 2016-03-07 20:21 UTC
