### ISSUE TITLE
Consider converting to default layoutBounds before PhET-iO publication

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balancing-act#138] opened 2023-05-19 16:37 UTC
This sim currently uses non-default `layoutBounds`.  In BASharedConstants.js:

```js
  LAYOUT_BOUNDS: new Bounds2( 0, 0, 768, 504 ),
```

Per https://github.com/phetsims/phet-io/issues/1939...  `layoutBounds` should not be changed for published PhET-iO sims because doing so may disrupt client customizations. So evaluate whether to change `layoutBounds` before publishing a PhET-iO version. 

If you decide not to change layoutBounds, document why in BASharedConstants.js, and refer to this issue.

**Comment by marlitas** [comment] 2023-11-30 22:39
This is a question that came up in Arithmetic as well, and can probably be answered the same for each.

**Comment by marlitas** [comment] 2023-11-30 22:51
The phet-io publication for this sim is long gone, and this issue is now a duplicate of #109. Closing

**Closed by marlitas** 2023-11-30 22:51 UTC
