### ISSUE TITLE
Cannot build a stable version

### ISSUE THREAD

**Issue by samreid** [phetsims/balancing-act#40] opened 2015-01-23 02:32 UTC
I received this report:

- Neither vibe nor vegas are present in http://phet.colorado.edu/sims/html/balancing-act/latest/dependencies.json

- I can't compile the balancing-act, due to the following error in kite/js/Shape (I've included the previous commands to ensure that I'm in the right version):

/var/www/a/sims/kite$ git rev-parse HEAD
11bccf0b11ff6152ee5a182c0a612b32ca7234a3

/var/www/a/sims/kite$ cd ../balancing-act/
/var/www/a/sims/balancing-act$ git rev-parse HEAD
d5ca5429cbee278c84ba3f2e63a89351c403a7ed

/var/www/a/sims/balancing-act$ grunt build
Running "generateLicenseInfo" task
created license info for 9 dependencies

Running "simBeforeRequirejs" task
Building simulation: balancing-act 1.0.1

Running "requirejs:build" (requirejs) task
>> Error: Error: ENOENT, no such file or directory '/var/www/a/sims/balancing-act/js/parser/svgPath.js'
>> In module tree:
>>     balancing-act-main
>>       BALANCING_ACT/intro/model/BAIntroModel
>>         BALANCING_ACT/common/model/BalanceModel
>>           BALANCING_ACT/common/model/Fulcrum
>>             KITE/Shape
>>
>>     at Object.fs.openSync (fs.js:410:18)
Warning: Task "requirejs:build" failed. Use --force to continue.

Aborted due to warnings.

The error comes from line 33 ( var svgPath = require( 'KITE/../parser/svgPath' ); ), solvable, but my feeling is that there is an error in the kite's SHA of dependencies.json.

**Comment by samreid** [comment] 2015-01-23 02:34
@jbphet when you have time can you look into the above issue?  Can you reproduce the problem?  Can the problem be fixed?  Is there a systemic problem with our builds that will cause this kind of problem in the future?

**Comment by jbphet** [comment] 2015-01-26 23:38
I'm not clear on what's going on here.  From whom did you receive the report above?  What are the circumstances?  I just went into the master version of balancing-act and built it via grunt with no issues.  There are two branches for this repo, 1.0 and arch.  Is the problem with building one of them?

**Comment by samreid** [comment] 2015-01-27 04:49
The client is trying to follow these instructions to build a stable version of Balancing Act:
https://docs.google.com/document/d/1odXkliRagq0zuf1_NdOtQ2BrkC9hwlISnPi2y-dKdrk/edit#bookmark=id.4fiykhwy31vk

I thought you might know if there was a problem with dependencies.json (I have a faint memory that some dependencies.json files were manually edited???)

**Comment by jbphet** [comment] 2015-02-02 19:43
I am not able to duplicate the precise error that the user is describing, but I am seeing a problem with the package.json file on the 1.0 branch of Balancing Act which does manifest as an inability to run the sim once built.  The package.json file is missing the dependencies on vegas and vibe, so the build process for version 1.0.1 didn't record the SHA values for these two libraries.  It doesn't quite explain what the user is seeing, but I will try fixing this issue and then working through the process described in the document linked above.

**Comment by jbphet** [comment] 2015-02-02 19:44
See #42 for tracking of the issue about missing dependencies.

**Comment by jbphet** [comment] 2015-02-02 20:35
I fixed the dependency issues for vegas and vibe (see #42), published a new RC version (see http://www.colorado.edu/physics/phet/dev/html/balancing-act/1.0.2/) and then used the new version to run through the steps described in the dev document linked above.  It all worked fine.  I think we should have the QA team do some regression testing on v1.0.2, publish it, then have this user try again.

Note that I still haven't seen the exact issue that this user described, so this may or may not fix their issue.  This is worth pursuing, though, since other potential developers may run into the same problems.

**Comment by jbphet** [comment] 2015-02-10 22:09
QA team completed their testing, and the maintenance release has been published.  I've also done a little editing of the document that I believe the user was working from.  Assigning to @samreid to request that the user try again.

**Comment by jbphet** [comment] 2015-02-23 21:58
Things are still not working for the user that reported this.  He is building on Linux, and I thought there could be an issue with this since none of our team has tried this and there have been other issues with Linux due to case sensitivity.  The user tried building on Mac, and hit the same problem.

**Comment by jbphet** [comment] 2015-02-23 22:00
The user suggested the following: 

> Delete node_modules folder and do a 'npm install', then build and see what happen. My guess is that require has changed the way to resolve relative paths going to parent folder.

I tried this and, indeed, I'm getting the error now.  Perhaps we need to be more restrictive about the version of require that we specify in our package.json files.

**Comment by pixelzoom** [comment] 2015-02-23 22:07
Are you seeing this for balancing-act only, or other sims after deleting node_modules?

**Comment by pixelzoom** [comment] 2015-02-23 22:08
@jbphet Are you seeing this for balancing-act only, or other sims after deleting node_modules?

**Comment by jbphet** [comment] 2015-02-23 22:11
I tried removing the tilde from the requirejs version specification in the dependencies.json file, in other words going from:
```js
"requirejs": "~2.1.8"
```
to
```js
"requirejs": "2.1.8"
```
then removing the node_modules directory and re-running ```npm install```.  This resolved the issue.   Yikes- this would seem to indicate that a minor release of the requirejs module broke this build.  I will discuss with the other PhET developers how to tackle this issue.

**Comment by pixelzoom** [comment] 2015-02-23 22:15
I removed node_modules and then built 'master' with no problems. So I'm guessing that this problem is specific to the branch that you're trying to build out of.

**Comment by pixelzoom** [comment] 2015-02-23 22:29
A clue: I see svgPath.js mentioned in the error message. svgPath.js is mentioned in chipper.Gruntfile.js.

**Comment by pixelzoom** [comment] 2015-02-23 23:15
I reproduced the problem on Mac OS.  Here's the complete set of steps (which seems somewhat convoluted).
 
% pwd
/you_working_directory/balancing-act/
% git status
git status
On branch 1.0
Your branch is up-to-date with 'origin/1.0'.

nothing to commit, working directory clean
% rm -rf node_modules
% npm install
...
% git checkout 1.0
Switched to branch '1.0'
Your branch is up-to-date with 'origin/1.0'.
% cp dependences.json ~/.
% git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
% mv ~/dependencies.json .
% grunt checkout-shas
....
Done, without errors.
% rm dependencies.json
% git checkout 1.0
Switched to branch '1.0'
Your branch is up-to-date with 'origin/1.0'.
cmalley@semitone[64]: grunt
Running "generateLicenseInfo" task
created license info for 9 dependencies

Running "jshint:simFiles" (jshint) task
>> 90 files lint free.

Running "jshint:commonFiles" (jshint) task
>> 371 files lint free.

Running "clean" task
Cleaning build directory

Running "generateLicenseInfo" task
created license info for 9 dependencies

Running "simBeforeRequirejs" task
Building simulation: balancing-act 1.0.2

Running "requirejs:build" (requirejs) task
>> Error: Error: ENOENT, no such file or directory '/Users/cmalley/PhET/GitHub/balancing-act/js/parser/svgPath.js'
>> In module tree:
>>     balancing-act-main
>>       BALANCING_ACT/intro/model/BAIntroModel
>>         BALANCING_ACT/common/model/BalanceModel
>>           BALANCING_ACT/common/model/Fulcrum
>>             KITE/Shape
>> 
>>     at Object.fs.openSync (fs.js:427:18)
Warning: Task "requirejs:build" failed. Use --force to continue.

Aborted due to warnings.
%

**Comment by pixelzoom** [comment] 2015-02-23 23:18
The error refers to `balancing-act/js/parser/svgPath.js`, this file lives in KITE at `kite/parser/svgPath.js` (not under js/, btw).

**Comment by pixelzoom** [comment] 2015-02-23 23:22
The manner in which KITE is importing svgPath.js also looks suspicious, see Shape.js in 11bccf0:

> var svgPath = require( 'KITE/../parser/svgPath' );

In master, this is:

> var svgPath = require( 'KITE/parser/svgPath' );

So I suspect that there was a build problem that was fixed in kite, and is still broken for balancing-act 1.0.

**Comment by pixelzoom** [comment] 2015-02-23 23:24
I see... In master, kite/parser/ was moved to kite/js/parser/.

**Comment by pixelzoom** [comment] 2015-02-23 23:34
Through bisection, I determined that this broke starting with requirejs 2.1.13. The release notes (http://requirejs.org/docs/download.html#releasenotes) say:

> 2.1.13
Version 2.1.12 regressed around ID normalization. 2.1.13 fixes that regression, and it is recommended that you do not use 2.1.12, but use 2.1.13 instead.

**Comment by pixelzoom** [comment] 2015-02-23 23:38
Here's the issue related to relative paths:

https://github.com/jrburke/requirejs/issues/1107

On the subject of relative paths (like the one causing problems here) it says:
> What is difficult is that when a module ID uses '..' at the beginning where it goes outside the module ID space. That is technically in undefined space. So the general advice is to avoid '..' at the beginning of a module ID. 

This was supposed to be resolved in requirejs 2.1.12, but apparently wasn't addressed properly (or in a way that affected PhET sims) until 2.1.13.

**Comment by pixelzoom** [comment] 2015-02-23 23:42
The recommended fix in this case is to change balancing-act/package.json in the '1.0' branch, so that `devDependencies` indicates a specific version of requirejs.  Any version prior to 2.1.13 will work. So, for example:

> "requirejs": "2.1.12"

**Comment by pixelzoom** [comment] 2015-02-23 23:51
kite.svgPath.js was relocated and relative path removed from its import in Shape.js in https://github.com/phetsims/kite/commit/c6a85af1513f2a9126a50dca4c03fb76e09a92fe on 5/28/2014. Any RC branches created before that date will be affected, and will likely fail with the same error when build with requirejs 2.1.13 or later.

**Comment by jbphet** [comment] 2015-02-24 00:00
I've replicated this issue on under-pressure, following the steps described in the document.  I chose this sim because it was released around the same time.

**Comment by pixelzoom** [comment] 2015-02-24 18:04
2/25/2015 dev meeting:

Consensus: Preferred fix is to change package.json (in branch) to use 1 specific version of requirejs (< 2.1.13). Don’t be proactive in fixing this, since we’ll be republishing everything for translations “sometime soon”.

**Comment by samreid** [comment] 2015-03-11 04:38
Not sure why this was assigned to me.  @jbphet anything else to do here?

**Comment by jbphet** [comment] 2015-03-11 18:08
I did two things:
+ I changed the PhET Development Overview document that the customer was using to refer to the acid-base-solutions sim instead of balancing-act, since acid-base-solution doesn't have the problem with its release that balancing-act has (since it was released after the Kite library was changed).
+ I updated the package.json file on the 1.0 branch of balancing-act.  This will correct the issue if we ever redeploy from this branch, but I didn't feel that redeploying it was worth the time and effort.

**Comment by jbphet** [comment] 2015-03-11 18:29
I also emailed the user that originally reported the issue and let him know about the actions that we've taken.

**Comment by jbphet** [comment] 2015-03-12 18:06
This issue was discussed in the 3/12/2015 meeting and we decided to close it.  We'll deal with the issue of there being a handful of sims that will have problems with trying to build the published version on a case by case basis if and when it comes up.

**Comment by jbphet** [comment] 2015-03-12 22:42
One last thing before closing: At the same dev meeting as mentioned in the previous comment, we also decided to use Area Builder instead of Acid Base Solutions as the example for obtaining stable code.  The PhET Development Overview has been edited to reflect this, and I want through the instructions to verify that building the latest released version works, and it does.  Closing.

**Closed by jbphet** 2015-03-12 22:42 UTC
