### ISSUE TITLE
Game will show most recent score instead of high score

### ISSUE THREAD

**Issue by BryceAG** [phetsims/balancing-act#63] opened 2016-01-22 19:25 UTC
Test device:
Bates, Disessa, Tycho

Operating System:
Windows 7, iOS 9.2, iOS 9.3 beta

Browser:
Chrome, Safari

Problem description:
If you play a level of the game and do worse than the previous time you played that level, it will show the more recent score instead of the high score like the other sims with games do.

Steps to reproduce:
Play a level and score at least one point, then play again and score less than the previous score.

Severity:

Screenshots:
Here I have 12 points in level one:
![image](https://cloud.githubusercontent.com/assets/15327201/12520575/96aceba8-c102-11e5-93ef-0dfc4bb0e10c.png)

Here I have 0 points without hitting the reset button:
![image](https://cloud.githubusercontent.com/assets/15327201/12520611/c63f5d4c-c102-11e5-80de-7ec350983f3f.png)

Troubleshooting information (do not edit):
Name: Balancing Act
URL: http://phet.colorado.edu/sims/html/balancing-act/latest/balancing-act_en.html
Version: 1.0.2
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36
Language: en-US
Window: 1366x667
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 9 uniform: 253
Texture: size: 8192 imageUnits: 16 (vertex: 4, combined: 20)
Max viewport: 8192x8192
OES_texture_float: true

**Comment by jbphet** [comment] 2016-03-16 18:46
The game was designed this way, but I believe we've undergone some evolution on our thinking on this since the last publication of this sim.  Assigning to @ariel-phet to say whether the current behavior should be retained (sim shows most recent results on level selection buttons) or changed to where the highest score is shown on the buttons.

**Comment by jbphet** [comment] 2016-03-16 22:34
I just checked Area Builder, and it also shows the most recent score, not the highest.

**Comment by jbphet** [comment] 2016-03-16 22:43
I just check Graphing Lines, and that shows highest score on level selection.  @phet-steele just checked Fraction Matcher, and that retains the high score as well.  This doesn't really seem to me like something that should vary from sim to sim.  @ariel-phet - we should make a call about what the PhET standard should be, high score or recent score, and the level selection buttons.

**Comment by ariel-phet** [comment] 2016-03-17 04:30
@phet-steele can you edit this list of sims with scored games with "stars" and level selection screens and note which paradigm they currently follow and then reassign to me

- **Area Builder** (retains last score)
- **Balancing Act** (retains last score)
- **Balancing Chemical Equations**
- **Build an Atom**
- **Fraction Matcher** (retains high score)
- **Graphing Lines** (retains high score)
- **RPAL**

**Comment by phet-steele** [comment] 2016-03-17 15:28
@ariel-phet there you go, I added Arithmetic.

**Comment by ariel-phet** [comment] 2016-03-18 17:30
This item would be good to discuss at status meeting and have a "codified" standard going forward.

1. As I recall the argument for retaining the high score was that is how many modern games work, however since we do not label the stars as "high score" or "best" this seems a bit unclear to the user.

2. For a classroom use I could see an advantage to always showing the most recent score, if you are asking a student to repeat a level/game several times.

Somewhat agnostic, but agree with @jbphet we should be consistent across games

**Comment by jbphet** [comment] 2016-03-30 16:14
This is the only remaining issue blocking a new RC for this sim, so I'm marking as high priority.  If we can't come to a consensus now, I can just publish using the current behavior, but I'd like for this to be a conscious decision.

**Comment by ariel-phet** [comment] 2016-03-31 17:01
At status meeting, @kathy-phet said that retaining most recent score should become our standard.

Reassigning to @jbphet (feel free to have @phet-steele make issues in other repos)

**Comment by jbphet** [comment] 2016-03-31 19:10
Closing, since we decided to standardize on the behavior currently implemented in this sim.

**Comment by pixelzoom** [comment] 2016-04-01 03:07
Reopening.

Several GitHub issues have been assigned to me to standardize this in other sims. So I'd like to add my 2 cents before making those changes.

Possible issues with showing the "recent score", instead of the "best score":

(1) There will be no record of what the student's highest score was on a level.

(2) There will be no way to know whether the student's current attempt at a level surpassed their previous high score.  In games, this is a big motivator for repeated play. 

(3) Once the student has achieved a perfect score, they will be disinclined to repeat the level, for fear of losing that high score on the level-selection screen.  

All of the above are the reason why "best score" is the standard in games. And the bottom line is that it motivates repeated play towards the goal of getting a perfect (or highest) score on all levels.

Assigning to @ariel-phet to review the above concerns. If they don't change anything, then simply comment and close this issue.

**Comment by pixelzoom** [comment] 2016-04-01 03:13
Also worth pointing out is that the tester thought that showing "recent score" was a bug. That's likely due to the fact that showing "recent score" is atypical behavior for games.

**Comment by pixelzoom** [comment] 2016-04-01 03:22
vegas.LevelSelectionButton has an optional "best time" display. In all of the sims that I've been asked to change (BCE, RPAL, Graphing Lines), we made a decision to show best time.  But if we're not showing best score, then why are we showing best time?  And how does a player have any chance of beating their best time if it's going to be wiped out along with their best score?

**Comment by pixelzoom** [comment] 2016-04-01 03:25
Arithmetic claims to follow the "recent score" standard. But I see in the code (LevelSelectionNode, lines 102 & 103) that it shows best time when the timer is enabled.  If it's showing best time and recent score, then the time has nothing to do with the displayed score.  That's totally confusing, and probably a bug.

**Comment by ariel-phet** [comment] 2016-04-01 05:26
@pixelzoom lets skype about this sometime

**Comment by pixelzoom** [comment] 2016-04-06 00:31
@ariel-phet asked me to:
(1) create a more general issue at https://github.com/phetsims/vegas/issues/51
(2) note the Arithmetic issue at https://github.com/phetsims/arithmetic/issues/173
(3) close this issue

**Comment by pixelzoom** [comment] 2017-03-21 17:44
Reopening, related to https://github.com/phetsims/graphing-lines/issues/61.  

@jbphet If you're showing recent scores, then does the model have `{Property.<number>[]} bestScore`?   At line 285 of BalanceGameModel, you're simply setting the level's best score to the most recent score:

```js
285  this.bestScores[ this.level ].value = this.score;
```

And you're also passing one of the Properties from `bestScore` to each level-selection button.

So it looks to me like you changed the semantics to "most-recent score", but left all of the variables names as "best".   This is misleading to say the least.

**Comment by pixelzoom** [comment] 2017-04-04 18:12
This sim also seems to be tracking "best time", see screenshot below.    If you're showing recent score, why you showing best time? That sure seems confusing - is it intentional? 

![screenshot_322](https://cloud.githubusercontent.com/assets/3046552/24671769/f2580ccc-192f-11e7-8e60-4d2aa5bacea1.png)

**Comment by ariel-phet** [comment] 2018-04-04 16:38
Removing assignee until sim is revisited

**Comment by marlitas** [comment] 2023-11-30 23:17
We probably want to revisit this for the upcoming publication, or at least confirm we're okay with what's going on right now. I don't know what the standard is right now. @kathy-phet can you help provide some clarity?

also my unasked two cents agrees with @pixelzoom... it seems bizarre to track most recent score and not highest score in a game.

**Comment by amanda-phet** [comment] 2023-12-15 18:51
Discussed in https://github.com/phetsims/vegas/issues/51#issuecomment-1858343945 

We'd like the level selection screen to show best score, not recent score.

**Comment by Luisav1** [comment] 2024-04-16 15:48
The best score is now shown on the level-selection screen. Closing.

**Comment by Luisav1** [comment] 2024-04-16 15:52
Reopening this issue because it's been a long-standing problem. It relates to standardizing the game score behavior across multiple simulations. Leaving it open for QA to review during dev testing seems like the best approach.

**Comment by Nancy-Salpepi** [comment] 2024-04-23 11:48
This looks good in 1.3.0-dev.1.
Closing!

**Closed by Nancy-Salpepi** 2024-04-23 11:48 UTC
Labels: type:bug, status:ready-for-review
