### ISSUE TITLE
KitSelectionNode should be deleted and Carousel should be used instead

### ISSUE THREAD

**Issue by samreid** [phetsims/balancing-act#97] opened 2020-01-17 20:54 UTC
KitSelectionNode was moved to scenery-phet, but is only used by balancing act.  It seems like Carousel should be used instead.  For https://github.com/phetsims/balancing-act/issues/96

@jbphet does that sound like it will work to you?  Any special features of KitSelectionNode that we will need to be careful to keep?

**Comment by samreid** [comment] 2020-01-18 06:12
In order to accomplish #96, I switched to use Carousel instead of KitSelectionNode.  Since this was the only usage of KitSelectionNode, I also deleted it and its no-longer-used components. This totaled around 400 lines of code we will no longer need to maintain or instrument for PhET-iO.  Unfortunately, the layouts are not exactly the same and will require fine-tuning, but that may not need to occur before #96.

**Comment by samreid** [comment] 2020-01-18 15:20
@ariel-phet can you please recommend a designer to look at the new usage of Carousel in Balancing Act, and recommend any design changes? It looks like this now:

![image](https://user-images.githubusercontent.com/679486/72666026-6abae900-39cb-11ea-8da0-d735c1e13913.png)

**Comment by jbphet** [comment] 2020-01-20 16:34
@samreid asked:

> @jbphet does that sound like it will work to you? 

Yes.  I believe all of this work pre-dated the existence of the common-code carousel, which is why it was like this.

> Any special features of KitSelectionNode that we will need to be careful to keep?

Not that I'm immediately aware of.  I think the thing that you noted above about changing the UI is what kept us from adopting it earlier.  Now that we have a motive, which is that it's easier for phet-io to use the more standard carousel, I'm fine with the changeover, though I have to admit that I prefer the previous look and feel.  I'll leave it to @ariel-phet to decide if we want to make some changes to carousel to make for more subtle buttons and thus preserve (at least to some degree) the previous appearance.

**Comment by ariel-phet** [comment] 2020-01-23 07:18
@samreid I think I can be that designer since I worked on balancing act extensively when it was produced.

A few things I think we need to tweak:

1. If we keep the current layout, the carousel buttons do need to have more of the original appearance IMO, right now they feel like that are "blocking" the user from dragging the objects into the play area. 

2. Generally our carousels have been used pulling objects up from the bottom of the screen, or from the side like in CCK, which could allow two potential alternative layouts
- One would be to use a vertical carousel in the current position so the buttons are top and bottom and the carousel pages scroll vertically, that would remove the "blocking" feel of the buttons, I am not a huge fan of this solution
- We could put a horizontal carousel along the bottom of the simulation and move the balance board up. The play area has lots of vertical space that really is not all that useful. A horizontal carousel could have several advantages, all the people could be on one page of the carousel, the bricks could be in ascending order left to right, and the mystery objects could be in alphabetical order left to right. In addition the intro screen could be changed so that the 3 objects were in a panel across the bottom of the screen. This paradigm is more in line with what has been used now in numerous simulations (like expression exchange, function builder, make a ten)

3. If we keep the layout as is and improve the buttons we will need the bricks and mystery objects to be more centered in the negative space.

**Comment by samreid** [comment] 2020-01-23 15:00
Can we please get feedback from @jbphet (lead developer of Balancing Act) and @pixelzoom (lead developer of Carousel) on the proposed ideas?

**Comment by pixelzoom** [comment] 2020-01-23 16:00
KitSelectionNode does indeed predate Carousel, see https://github.com/phetsims/sun/issues/166. That's also the issue where Carousel was designed, if you're interested in design history. 

There doesn't seem to be any question that moving to Carousel is appropriate, especially in light of PhET-iO and a11y instrumentation.

I haven't been involved in the design or implementation of this sim, so I will defer on BA design proposals.   

Whatever is decided, I would encourage you not to create more options for Carousel. Some of the proposals seem to be headed in that direction.  E.g. "the carousel buttons do need to have more of the original appearance". It would be preferable to have one "appearance" for all Carousel buttons - it will simplify implementation and provide UX consistency. 

I'll also note that there are other features required by BA (page layout and page title) that are not supported by Carousel, and have not been discussed here.  Those (and other) features were called out in https://github.com/phetsims/sun/issues/541, and would necessitate a rewrite of Carousel.  If you're going to do that rewrite, then consider BA's design when formulating the new Carousel requirements.

**Comment by pixelzoom** [comment] 2020-01-23 16:10
Based on this issue and phetsims/sun#541, it seems like a design meeting specific to Carousel is needed.

**Comment by samreid** [comment] 2020-01-23 18:12
Today we agreed a good solution for now would be to change the look of the buttons:

```diff
Index: js/Carousel.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/Carousel.js	(revision bdc7086fd884fec6b371eaa15c793db437af0b0c)
+++ js/Carousel.js	(date 1579802917724)
@@ -111,9 +111,9 @@
       xMargin: 5,
       yMargin: 5,
       cornerRadius: options.cornerRadius,
-      baseColor: options.buttonColor,
+      baseColor: null,
       disabledBaseColor: options.fill, // same as carousel background
-      stroke: options.buttonStroke,
+      stroke: null,
       lineWidth: options.buttonLineWidth,
       minWidth: isHorizontal ? 0 : maxItemWidth + ( 2 * options.margin ), // fill the width of a vertical carousel
       minHeight: isHorizontal ? maxItemHeight + ( 2 * options.margin ) : 0, // fill the height of a horizontal carousel
```

![image](https://user-images.githubusercontent.com/679486/73011291-30898700-3dd1-11ea-8281-876aea662dba.png)

**Comment by pixelzoom** [comment] 2020-01-23 18:16
To clarify the above patch...  We did not decide to make this change in Carousel.  BAA will pass in options `baseColor: null` and `stroke: null` for its Carousel instance.

**Comment by samreid** [comment] 2020-01-28 03:14
I added the lightweight look, @ariel-phet can you please review on phettest?  Anything else for this issue other than scheduling a carousel design meeting as described in https://github.com/phetsims/balancing-act/issues/97#issuecomment-577746292 ?

**Comment by ariel-phet** [comment] 2020-01-28 04:25
@samreid if possible it would be better to center the bricks and the mystery objects more in the white space of the carousel page, but not critical for the current iO release.

**Comment by samreid** [comment] 2020-01-30 14:59
I used nested `AlignGroup` to better center the bricks and mystery objects, please review on phettest at your convenience.

**Comment by ariel-phet** [comment] 2020-01-30 18:29
@samreid looking good to me, closing

**Closed by ariel-phet** 2020-01-30 18:29 UTC
Labels: design:general, status:ready-for-review
